interval = 300
splay = 180
log_level = "warn"
env_path_prefix = "/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin"
ssl_verify_mode = ":verify_none"

[data_collector]
enable = "true"
token = "pnIT28d_Xp47A1MZt9m5Aow5rdk="
server_url = "https://ec2-13-237-222-164.ap-southeast-2.compute.amazonaws.com/data-collector/v0/"